export const EDIT_EQUIPMENT_ACTION_TYPES = {
    FETCH_GET_EQUIPMENTS_SUCCESS: "FETCH_GET_EQUIPMENTS_SUCCESS",
    ADD_CURRENT_EQUIPMENT: "ADD_CURRENT_EQUIPMENT",
    RESET_EQUIPMENTS: "RESET_EQUIPMENTS"
}