export const EDIT_EQUIPMENT_TYPE_ACTION_TYPES = {
    FETCH_GET_EQUIPMENT_TYPES_SUCCESS: "FETCH_GET_EQUIPMENT_TYPES_SUCCESS",
    ADD_CURRENT_EQUIPMENT_TYPE: "ADD_CURRENT_EQUIPMENT_TYPE",
    RESET_EQUIPMENT_TYPE: "RESET_EQUIPMENT_TYPE"
}