export const ASSIGN_EQUIPMENT_ACTION_TYPES = {
    FETCH_GET_ASSIGN_EQUIPMENT_SUCCESS: "FETCH_GET_ASSIGN_EQUIPMENT_SUCCESS",
    ADD_CURRENT_ASSIGN_EQUIPMENT: "ADD_CURRENT_ASSIGN_EQUIPMENT",
    RESET_ASSIGN_EQUIPMENT: "RESET_ASSIGN_EQUIPMENT"
}