export const EDIT_COLLABORATER_ACTION_TYPES = {
    FETCH_GET_COLLABORATERS_SUCCESS: "FETCH_GET_COLLABORATERS_SUCCESS",
    ADD_CURRENT_COLLABORATER: "ADD_CURRENT_COLLABORATER",
    RESET_COLLABORATERS: "RESET_COLLABORATERS"
}